### ISSUE TITLE
Rails 5 beta / Ruby 2.2.2: NoMethodError: undefined method `seed' for SeedFu:Module

### ISSUE THREAD

**Issue by psunix** [mbleigh/seed-fu#104]
hi

just bootstrapped my first Rails 5 app and added the seed_fu gem.

when I try to call SeedFu.seed I receive the following error:

```
2.2.2 :001 > SeedFu.seed
NoMethodError: undefined method `seed' for SeedFu:Module
        from (irb):1
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.beta3/lib/rails/commands/console.rb:65:in `start'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.beta3/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `block in require'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
        from /home/ps/git/atum/atum-backend/bin/rails:9:in `<top (required)>'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `block in load'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/commands/rails.rb:6:in `call'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/command_wrapper.rb:38:in `call'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application.rb:185:in `block in serve'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application.rb:156:in `fork'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application.rb:156:in `serve'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
        from /home/ps/.rvm/gems/ruby-2.2.2/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /home/ps/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/ps/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'2.2.2 :002 > 

```
Full Rails app is available here: https://github.com/psunix/atum-backend

Since I have other Rails 4 projects where this works it might be a bug.

**Comment by aserafin** [comment]
@psunix - thanks for the report

I've created test project with Rails 5.0.0 version released today and above works fine for me. I'm closing this ticket but please free to ping me if it is still a problem for you.
